{
  config,
  inputs,
  lib,
  ...
}:
let
  hostLib = import ./host.nix { inherit lib; };

  nixpkgsConfig = {
    allowUnfreePredicate = import ../non-module/allowUnfreePredicate.nix;
  };

  mkNixosFromHost =
    { host }:
    let
      hasDiskoConfig = host.disk.configSource == "disko" && host.disk.disko != null;
    in
    inputs.nixpkgs.lib.nixosSystem {
      inherit (host) system;
      specialArgs = {
        inherit inputs;
      };
      modules = [
        {
          nixpkgs.config = nixpkgsConfig;
        }
        inputs.stylix.nixosModules.stylix
        inputs.home-manager.nixosModules.home-manager
        ../nixos
        ./nixos.nix
        (
          { ... }:
          {
            options.my = lib.mkOption {
              type = lib.types.submodule hostLib.module;
            };

            config = {
              my = host;
              home-manager = {
                useGlobalPkgs = true;
                useUserPackages = true;
                extraSpecialArgs = {
                  inherit inputs;
                };
                users."${host.username}" = {
                  imports = [
                    ../home
                    {
                      options.my = lib.mkOption {
                        type = lib.types.submodule hostLib.module;
                      };

                      config.my = host;
                    }
                  ]
                  ++ host.homeModules;
                };
              };
            }
            // lib.optionalAttrs hasDiskoConfig {
              disko = host.disk.disko;
            };
          }
        )
      ]
      ++ (if hasDiskoConfig then [ inputs.disko.nixosModules.disko ] else [ ])
      ++ host.modules
      ++ (
        if host.disk.configSource == "hardware-configuration.nix" then
          [ host.disk.hardware-configuration ]
        else
          [ ]
      );
    };
in
{
  options.my.hosts = lib.mkOption {
    type = lib.types.lazyAttrsOf (lib.types.submodule hostLib.module);
    default = { };
    description = "NixOS hosts generated by this flake.";
  };

  config.flake.lib = {
    inherit mkNixosFromHost;
    host = hostLib;
  };

  config.flake.nixosConfigurations = (
    lib.mapAttrs' (
      name: host:
      lib.nameValuePair name (mkNixosFromHost {
        host = host;
      })
    ) config.my.hosts
  );

  config.perSystem =
    {
      pkgs,
      ...
    }:
    {
      apps = lib.mapAttrs' (
        name: host:
        let
          nixosConfiguration = mkNixosFromHost {
            host = host // {
              isVm = true;
            };
          };
          runVm = pkgs.writeShellApplication {
            name = "run-${name}-vm";
            text = ''
              if [ -z "''${TMPDIR:-}" ] || [ ! -d "$TMPDIR" ]; then
                export TMPDIR=/tmp
              fi

              exec ${nixosConfiguration.config.system.build.vm}/bin/run-${nixosConfiguration.config.networking.hostName}-vm "$@"
            '';
          };
        in
        lib.nameValuePair "${name}-vm" {
          type = "app";
          program = "${runVm}/bin/run-${name}-vm";
        }
      ) config.my.hosts;
    };
}
