{
  config,
  inputs,
  lib,
  ...
}:
let
  hostLib = import ./host { inherit lib; };

  mkNixosFromHost =
    {
      host,
      isVm,
    }:
    inputs.nixpkgs.lib.nixosSystem {
      inherit (host) system;
      specialArgs = {
        inherit inputs;
      };
      modules = [
        inputs.home-manager.nixosModules.home-manager
        ../nixos
        (
          { ... }:
          {
            options.my = lib.mkOption {
              type = lib.types.submodule hostLib.module;
            };

            config = {
              my = host;

              home-manager = {
                useGlobalPkgs = true;
                useUserPackages = true;
                extraSpecialArgs = {
                  inherit inputs;
                };
                users."${host.username}" = {
                  imports = [
                    ../home
                    {
                      options.my = lib.mkOption {
                        type = lib.types.submodule hostLib.module;
                      };

                      config.my = host;
                    }
                  ]
                  ++ host.homeModules;
                };
              };
            };
          }
        )
        (
          { ... }:
          {
            my.isVm = isVm;
          }
        )
      ]
      ++ host.modules;
    };
in
{
  options.my.hosts = lib.mkOption {
    type = lib.types.lazyAttrsOf (lib.types.submodule hostLib.module);
    default = { };
    description = "NixOS hosts generated by this flake.";
  };

  config.flake.lib = {
    inherit mkNixosFromHost;
    host = hostLib;
  };

  config.flake.nixosConfigurations = (
    lib.mapAttrs' (
      name: host:
      lib.nameValuePair name (mkNixosFromHost {
        host = host;
        isVm = false;
      })
    ) config.my.hosts
  );

  config.perSystem =
    {
      ...
    }:
    {
      apps = lib.mapAttrs' (
        name: host:
        let
          nixosConfiguration = mkNixosFromHost {
            host = host;
            isVm = true;
          };
        in
        lib.nameValuePair "${name}-vm" {
          type = "app";
          program = "${nixosConfiguration.config.system.build.vm}/bin/run-${nixosConfiguration.config.networking.hostName}-vm";
        }
      ) config.my.hosts;
    };
}
