exec-once = @waybar@
exec-once = @mako@
exec-once = @hyprland-autoname-workspaces@
exec-once = @kitty@ --title hyprland-ready @zsh@ -lc 'echo "Hyprland is running."; echo "Super+Return opens a terminal."; exec @zsh@'
