bind = $mod, Return, exec, $terminal
bind = $mod Shift, q, killactive
bind = $mod, d, exec, @wofi@ --show drun
bind = $mod, s, setfloating
bind = $mod, w, settiled
bind = $mod, e, togglesplit
bind = $mod, f, fullscreen, toggle
bind = $mod, c, movecurrentworkspacetomonitor, +1
bind = , Print, exec, @hypr-screenshot@
bind = $mod, Print, exec, @hypr-screen-record@
bind = Shift, Print, exec, @hypr-screenshot@ area
bind = $mod Shift, Print, exec, @hypr-screen-record@ area

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

bind = $mod Shift, 1, movetoworkspace, 1
bind = $mod Shift, 2, movetoworkspace, 2
bind = $mod Shift, 3, movetoworkspace, 3
bind = $mod Shift, 4, movetoworkspace, 4
bind = $mod Shift, 5, movetoworkspace, 5
bind = $mod Shift, 6, movetoworkspace, 6
bind = $mod Shift, 7, movetoworkspace, 7
bind = $mod Shift, 8, movetoworkspace, 8
bind = $mod Shift, 9, movetoworkspace, 9
bind = $mod Shift, 0, movetoworkspace, 10

bindm = $mod, mouse:272, movewindow
